//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dishes.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int ProductID { get; set; }
        public string NameProduct { get; set; }
        public string DescriptionProduct { get; set; }
        public string ManufacturerProduct { get; set; }
        public Nullable<double> CostProduct { get; set; }
        public Nullable<double> DiscountProduct { get; set; }
        public Nullable<int> QuantityInWarehouse { get; set; }
        public string isInWarehouse
        {
            get
            {
                if(this.QuantityInWarehouse > 0)
                {
                    return "Есть на складе";
                }
                else
                {
                    return "Нет на складе";
                }
                 
            }
        }
        public SolidColorBrush colorBrush
        {
            get
            {
                if (this.QuantityInWarehouse > 0)
                {
                    return Brushes.Green;
                }
                else
                {
                    return Brushes.Gray;
                }
            }
        }
        public Nullable<int> CategoryProduct { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
